---
title: "Probabilidade e EstatĂ­stica"
subtitle: "Probabilidade de Eventos"
author: "Prof. Dr. Alessandro JQ Sarnaglia"
lang: "pt"
format:
  revealjs:
    width: 1280
    height: 720
    fig-width: 5.5
    fig-height: 5.5
    theme: [custom.scss]
    css: fonts.css
    callout-icon: false
    toc: true
    toc-depth: 3
    toc-expand: 3
    number-sections: true
    number-depth: 3
    footer: "[Voltar đź”™](../index.html)"
    menu:
      useTextContentForMissingTitles: false
editor: source
filters:
  - parse-latex
---

```{r}
library(xtable)
library(gt)
library(gtsummary)
tab_op <- function(tbl){
  tab_options(data = tbl,
              table.font.size = "100%",
              table.border.top.color="#000000",
              table.border.bottom.color = "#000000",
              table.border.top.width = "1px",
              table.border.bottom.width = "1px",
              column_labels.border.top.color="#000000",
              column_labels.border.bottom.color="#000000",
              column_labels.border.top.width = "1px",
              column_labels.border.bottom.width = "1px",
              row_group.border.top.color = "#000000",
              row_group.border.bottom.color = "#000000",
              row_group.border.top.width = "1px",
              row_group.border.bottom.width = "1px",
              table_body.border.top.color = "#000000",
              table_body.border.bottom.color = "#000000",
              table_body.border.top.width = "1px",
              table_body.border.bottom.width = "1px",
              summary_row.border.color = "#000000",
              summary_row.border.width = "1px",
              table_body.hlines.color = "#000000",
              table_body.hlines.width = "1px")
}
```

# Experimentos AleatĂłrios

## Experimentos AleatĂłrios {.unnumbered .unlisted}

Ao medir a corrente em um fio, estamos conduzindo um **experimento**.

::: {.callout-tip .fragment}
## Fato

Se repetirmos o experimento acima diversas vezes, observaremos que os resultados diferem levemente de uma repetiĂ§ĂŁo para outra.
:::

::: fragment

Isso ocorre, pois vĂˇrios fatores podem influenciar o resultado. Por exemplo:

:::

::: incremental

-   VariaĂ§Ăµes na temperatura ambiente no momento da realizaĂ§ĂŁo;
-   VariaĂ§Ăµes nos equipamentos utilizados para realizar a mediĂ§ĂŁo;
-   Impurezas na composiĂ§ĂŁo quĂ­mica do fio;
-   Impulsos na fonte da corrente.

:::

## Experimentos AleatĂłrios {.unnumbered .unlisted}

NĂŁo importa quanto cuidado teremos no planejamento e na conduĂ§ĂŁo do experimento, sempre existem variĂˇveis de peturbaĂ§ĂŁo (ou ruĂ­do) que nĂŁo sĂŁo controladas.

::: fragment

Isso provoca aleatoriedade (ou incerteza) dos resultados obtidos em diferentes realizaĂ§Ăµes do experimento.

:::

::: {.callout-note .fragment}
## DefiniĂ§ĂŁo

Dizemos que um experimento Ă© aleatĂłrio se, mesmo quando repetido sob "condiĂ§Ăµes idĂŞnticas", nĂŁo Ă© possĂ­vel predizer com absoluta certeza o seu resultado. Vamos denotar um experimento aleatĂłrio por $\mathcal{E}$.
:::

## EspaĂ§o amostral

Devido a sua natureza, nĂŁo Ă© possĂ­vel antever com absoluta certeza o resultado de um experimento aleatĂłrio

::: fragment

Exemplos:

:::

::: incremental

-   $\mathcal{E}_1$ = "uma peĂ§a Ă© fabricada em uma linha de produĂ§ĂŁo e, depois de inspecionada, Ă© classificada como *defeituosa* ($D$) ou *nĂŁo defeituosa* ($N$)";
-   $\mathcal{E}_2$ = "o nĂşmero de ligaĂ§Ăµes que chega em determinado dia a um call center Ă© observado";
-   $\mathcal{E}_3$ = "o tempo em minutos necessĂˇrio para realizar uma reaĂ§ĂŁo quĂ­mica Ă© observado".

:::

## EspaĂ§o amostral {.unnumbered .unlisted}

::: {.callout-tip .fragment}
## ObservaĂ§ĂŁo

Embora nĂŁo saibamos o resultado que um experimento fornecerĂˇ, devemos poder listar todos os seus possĂ­veis resultados
:::

::: {.callout-note .fragment}
## DefiniĂ§ĂŁo

O [conjunto de todos]{.underline} possĂ­veis resultados de um experimento aleatĂłrio Ă© denominado **espaĂ§o amostral** e Ă© denotado por $\Omega$.
:::


## Eventos

# Modelo ProbabilĂ­stico 

## Ălgebra de Eventos

## Medida de Probabilidade

## Propriedades

# Probabilidade Condicional

## Probabilidade Condicional {.unnumbered .unlisted}

## IndependĂŞncia

## Teorema da Probabilidade Total

## Teorema de Bayes

# FIM {.unnumbered .unlisted}
